/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.ifmg.projeto_impressora.view.gerenciaveis;

import com.ifmg.projeto_impressora.controller.LocalController;
import com.ifmg.projeto_impressora.controller.RelatorioController;
import com.ifmg.projeto_impressora.controller.ImpressoraController;
import com.ifmg.projeto_impressora.controller.ProprietarioController;
import com.ifmg.projeto_impressora.controller.LtdConsController;
import com.ifmg.projeto_impressora.model.Impressora;
import com.ifmg.projeto_impressora.model.Proprietario;
import com.ifmg.projeto_impressora.model.exceptions.ImpressoraException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author iago_
 */
public class IFrImpressora extends javax.swing.JInternalFrame {

    ImpressoraController impressoraController;
    LocalController localController;
    ProprietarioController propController;
    LtdConsController fornecedorController;
    RelatorioController tecnicoController;
    int idImpressoraEditando;

    /**
     * Creates new form IFrEquino
     */
    public IFrImpressora() {

        impressoraController = new ImpressoraController();
        localController = new LocalController();
        propController = new ProprietarioController();
        fornecedorController = new LtdConsController();
        tecnicoController = new RelatorioController();
        idImpressoraEditando = -1;
        

        initComponents();
        
        
        habilitarCampos(false);
        limparCampos();
        localCombobox();
        proprietarioCombobox();
        fornecedorCombobox();
        tecnicoCombobox();

        impressoraController.atualizarTabela(grdImpressoras);

    }

    public void localCombobox() {
        cbxLocal.addItem("");
        String[] locaisString = localController.buscarLocalString().split("\n");

        for (String localId : locaisString) {
            cbxLocal.addItem(localId);
        }
    }

    public void proprietarioCombobox() {
        cbxProprietario.addItem("");
        String[] proprietarioIdNomeString = propController.buscarProprietariosString().split("\n");

        for (String idNome : proprietarioIdNomeString) {
            cbxProprietario.addItem(idNome);
        }
    }

    public void fornecedorCombobox() {
        cbxFornecedor.addItem("");
        String[] veterinarioIdNomeString = fornecedorController.buscarLtdsString().split("\n");

        for (String idNome : veterinarioIdNomeString) {
            cbxFornecedor.addItem(idNome);
        }
    }

    public void tecnicoCombobox() {
        cbxTecnico.addItem("");
        String[] veterinarioIdNomeString = tecnicoController.buscarTecnicosString().split("\n");

        for (String idNome : veterinarioIdNomeString) {
            cbxTecnico.addItem(idNome);
        }
    }

    public Integer getIdDoidNome(String idNome) {
        String[] novoIdNome = idNome.split(" - ");
        return Integer.parseInt(novoIdNome[0]);
    }

    public void habilitarCampos(boolean flag) {
        edtNome.setEnabled(flag);       
        edtMarca.setEnabled(flag);
        edtDataFab.setEnabled(flag);
        cbxLocal.setEnabled(flag);
        cbxTecnico.setEnabled(flag);
        cbxFornecedor.setEnabled(flag);
        cbxProprietario.setEnabled(flag);
    }

    public void limparCampos() {
        edtNome.setText("");        
        edtMarca.setText("");
        edtDataFab.setText("");
    }

    public void preencherFormulario(Impressora e) {
        edtNome.setText(e.getNome());        
        edtMarca.setText(e.getMarca());
        edtDataFab.setText(String.valueOf(e.getDataFabricacao()));
        
         if(e.getLocal()!= null){
            cbxLocal.getModel().setSelectedItem(String.valueOf(e.getLocal().getId()));
        }
        
        
        if(e.getProprietario() != null){
            cbxProprietario.getModel().setSelectedItem(e.getProprietario().getId() + " - " + e.getProprietario().getNome());
        }
        if(e.getTecnico()!= null){
            cbxTecnico.getModel().setSelectedItem(e.getTecnico().getId() + " - " + e.getTecnico().getNome());
        }
        
        if(e.getLtdCons()!= null){
            cbxFornecedor.getModel().setSelectedItem(e.getLtdCons().getId() + " - " + e.getLtdCons().getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdImpressoras = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblDataFab = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtMarca = new javax.swing.JTextField();
        cbxProprietario = new javax.swing.JComboBox<>();
        lblProprietario = new javax.swing.JLabel();
        cbxTecnico = new javax.swing.JComboBox<>();
        lblTecnico = new javax.swing.JLabel();
        cbxFornecedor = new javax.swing.JComboBox<>();
        lblFornecedor = new javax.swing.JLabel();
        cbxLocal = new javax.swing.JComboBox<>();
        lblLocal = new javax.swing.JLabel();
        edtDataFab = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);

        grdImpressoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdImpressoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdImpressorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdImpressoras);

        lblNome.setText("Nome:");

        lblMarca.setText("Marca:");

        lblDataFab.setText("Data Fabricação:");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gerenciamento das Impressoras");

        lblProprietario.setText("Proprietário:");

        lblTecnico.setText("Tecnico:");

        lblFornecedor.setText("Fornecedor:");

        lblLocal.setText("Local:");

        try {
            edtDataFab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbxFornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblProprietario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxProprietario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFornecedor)
                    .addComponent(lblNome)
                    .addComponent(lblMarca))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTecnico)
                    .addComponent(lblDataFab)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbxTecnico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLocal)
                        .addComponent(cbxLocal, 0, 208, Short.MAX_VALUE)
                        .addComponent(edtDataFab)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblDataFab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDataFab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(lblTecnico))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProprietario)
                    .addComponent(lblLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(lblFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        idImpressoraEditando = -1;
        this.habilitarCampos(true);
        this.limparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Impressora equinoEditando = (Impressora) this.getObjectSelectOnGrid();

        if (equinoEditando == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            try {
                impressoraController.excluirEquino(equinoEditando);

                impressoraController.atualizarTabela(grdImpressoras);
                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
            } catch (ImpressoraException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Impressora equinoEditando = (Impressora) this.getObjectSelectOnGrid();
        if (equinoEditando == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            this.limparCampos();
            this.habilitarCampos(true);
            this.preencherFormulario(equinoEditando);
            this.idImpressoraEditando = equinoEditando.getId();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(cbxTecnico.getSelectedItem().equals("")){
            System.out.println("RETORNA NADA");
        }
        String prop = String.valueOf(cbxProprietario.getSelectedItem());
        String tecnico = String.valueOf(cbxTecnico.getSelectedItem());
        String local = String.valueOf(cbxLocal.getSelectedItem());
        String ltdCons = String.valueOf(cbxFornecedor.getSelectedItem());

        try {
            if (idImpressoraEditando > 0) {
                impressoraController.atualizarImpressora(
                        idImpressoraEditando, edtNome.getText(), edtMarca.getText(),
                        edtDataFab.getText(), prop, ltdCons, local, tecnico
                );
                idImpressoraEditando = -1;
            } else {
                impressoraController.cadastrarImpressora(
                        edtNome.getText(),  edtMarca.getText(),
                        edtDataFab.getText(), prop, ltdCons, local, tecnico
                );
            }

            impressoraController.atualizarTabela(grdImpressoras);
            this.habilitarCampos(false);
            this.limparCampos();
        } catch (ImpressoraException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void grdImpressorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdImpressorasMouseClicked
        if (evt.getClickCount() == 2) {
            btnEditarActionPerformed(null);
        }
    }//GEN-LAST:event_grdImpressorasMouseClicked

    private Object getObjectSelectOnGrid() {
        int rowCliked = grdImpressoras.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdImpressoras.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxFornecedor;
    private javax.swing.JComboBox<String> cbxLocal;
    private javax.swing.JComboBox<String> cbxProprietario;
    private javax.swing.JComboBox<String> cbxTecnico;
    private javax.swing.JFormattedTextField edtDataFab;
    private javax.swing.JTextField edtMarca;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTable grdImpressoras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataFab;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
