/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifmg.projeto_impressora.view;

import com.ifmg.projeto_impressora.view.gerenciaveis.IFrFornecedor;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrLocal;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrTecnico;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrImpressora;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrProprietario;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrServicoAdicional;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrLtdCons;
import com.ifmg.projeto_impressora.view.gerenciaveis.IFrPagarFatura;
import javax.swing.JFrame;

/**
 *
 * @author gusta
 */
public class FrAdministrador extends javax.swing.JFrame {

    private JFrame telaAnterior;
    /**
     * Creates new form FrAdministrador
     * @param telaQueChamou
     */
    public FrAdministrador(JFrame telaQueChamou) {
        this.telaAnterior = telaQueChamou;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPaneAdm = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        mnItemGerenciarImpressora = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitemGerenciarProprietario = new javax.swing.JMenuItem();
        mitemPagarFatura = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitemGerenciarTecnico = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitemGerenciarLtdCon = new javax.swing.JMenuItem();
        menuLocal = new javax.swing.JMenu();
        mitemGerenciarLocal = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenu();
        mitemGerenciarAlimento = new javax.swing.JMenuItem();
        mitemGerenciarSerAdicionais = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout deskPaneAdmLayout = new javax.swing.GroupLayout(deskPaneAdm);
        deskPaneAdm.setLayout(deskPaneAdmLayout);
        deskPaneAdmLayout.setHorizontalGroup(
            deskPaneAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        deskPaneAdmLayout.setVerticalGroup(
            deskPaneAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        menuAdministrador.setText("Impressora");

        mnItemGerenciarImpressora.setText("Gerenciar");
        mnItemGerenciarImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemGerenciarImpressoraActionPerformed(evt);
            }
        });
        menuAdministrador.add(mnItemGerenciarImpressora);

        jMenuBar1.add(menuAdministrador);

        jMenu2.setText("Proprietário");

        mitemGerenciarProprietario.setText("Gerenciar");
        mitemGerenciarProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemGerenciarProprietarioActionPerformed(evt);
            }
        });
        jMenu2.add(mitemGerenciarProprietario);

        mitemPagarFatura.setText("Pagar fatura");
        mitemPagarFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemPagarFaturaActionPerformed(evt);
            }
        });
        jMenu2.add(mitemPagarFatura);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tecnico");

        mitemGerenciarTecnico.setText("Gerenciar");
        mitemGerenciarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemGerenciarTecnicoActionPerformed(evt);
            }
        });
        jMenu3.add(mitemGerenciarTecnico);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Conserto");

        mitemGerenciarLtdCon.setText("Gerenciar");
        mitemGerenciarLtdCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemGerenciarLtdConActionPerformed(evt);
            }
        });
        jMenu4.add(mitemGerenciarLtdCon);

        jMenuBar1.add(jMenu4);

        menuLocal.setText("Local");

        mitemGerenciarLocal.setText("Gerenciar");
        mitemGerenciarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemGerenciarLocalActionPerformed(evt);
            }
        });
        menuLocal.add(mitemGerenciarLocal);

        jMenuBar1.add(menuLocal);

        menuFornecedor.setText("Fornecedor");

        mitemGerenciarAlimento.setText("Gerenciar");
        mitemGerenciarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemGerenciarAlimentoActionPerformed(evt);
            }
        });
        menuFornecedor.add(mitemGerenciarAlimento);

        jMenuBar1.add(menuFornecedor);

        mitemGerenciarSerAdicionais.setText("Serviços adicionais");

        jMenuItem1.setText("Gerenciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mitemGerenciarSerAdicionais.add(jMenuItem1);

        jMenuBar1.add(mitemGerenciarSerAdicionais);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deskPaneAdm)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deskPaneAdm)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemGerenciarImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemGerenciarImpressoraActionPerformed
        IFrImpressora ifrEquino = new IFrImpressora();
        deskPaneAdm.add(ifrEquino);
        ifrEquino.setVisible(true);
    }//GEN-LAST:event_mnItemGerenciarImpressoraActionPerformed

    private void mitemGerenciarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemGerenciarLocalActionPerformed
        IFrLocal ifrBaia = new IFrLocal();
        deskPaneAdm.add(ifrBaia);
        ifrBaia.setVisible(true);
    }//GEN-LAST:event_mitemGerenciarLocalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void mitemGerenciarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemGerenciarAlimentoActionPerformed
        IFrFornecedor ifrAlimento = new IFrFornecedor();
        deskPaneAdm.add(ifrAlimento);
        ifrAlimento.setVisible(true);
    }//GEN-LAST:event_mitemGerenciarAlimentoActionPerformed

    private void mitemGerenciarLtdConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemGerenciarLtdConActionPerformed
        IFrLtdCons ifrVeterinario = new IFrLtdCons();
        deskPaneAdm.add(ifrVeterinario);
        ifrVeterinario.setVisible(true);
    }//GEN-LAST:event_mitemGerenciarLtdConActionPerformed

    private void mitemGerenciarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemGerenciarTecnicoActionPerformed
        IFrTecnico ifrTecnico = new IFrTecnico();
        deskPaneAdm.add(ifrTecnico);
        ifrTecnico.setVisible(true);
    }//GEN-LAST:event_mitemGerenciarTecnicoActionPerformed

    private void mitemGerenciarProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemGerenciarProprietarioActionPerformed
        IFrProprietario ifrProprietario = new IFrProprietario();
        deskPaneAdm.add(ifrProprietario);
        ifrProprietario.setVisible(true);
    }//GEN-LAST:event_mitemGerenciarProprietarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IFrServicoAdicional ifrServicoAdicional = new IFrServicoAdicional();
        deskPaneAdm.add(ifrServicoAdicional);
        ifrServicoAdicional.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mitemPagarFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemPagarFaturaActionPerformed
        IFrPagarFatura ifrPagarFatura = new IFrPagarFatura();
        deskPaneAdm.add(ifrPagarFatura);
        ifrPagarFatura.setVisible(true);
    }//GEN-LAST:event_mitemPagarFaturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPaneAdm;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenu menuLocal;
    private javax.swing.JMenuItem mitemGerenciarAlimento;
    private javax.swing.JMenuItem mitemGerenciarLocal;
    private javax.swing.JMenuItem mitemGerenciarLtdCon;
    private javax.swing.JMenuItem mitemGerenciarProprietario;
    private javax.swing.JMenu mitemGerenciarSerAdicionais;
    private javax.swing.JMenuItem mitemGerenciarTecnico;
    private javax.swing.JMenuItem mitemPagarFatura;
    private javax.swing.JMenuItem mnItemGerenciarImpressora;
    // End of variables declaration//GEN-END:variables
}
