/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifmg.projeto_impressora.view;

import com.ifmg.projeto_impressora.model.auth.Autenticador;
import com.ifmg.projeto_impressora.controller.RelatorioController;
import com.ifmg.projeto_impressora.model.Fornecedor;
import com.ifmg.projeto_impressora.model.Impressora;
import com.ifmg.projeto_impressora.model.ImpressoraServico;
import com.ifmg.projeto_impressora.model.ServicoAdicional;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author iago_
 */
public class FrTecnico extends javax.swing.JFrame {

    RelatorioController tecnicoController;

    public FrTecnico() {
        tecnicoController = new RelatorioController();
        initComponents();
        tecnicoController.atualizarTabelaImpressora(grdImpressora, Autenticador.getIdLogado());
    }
    
    private void preencherListaFornecedor(){
        Impressora impressoraTab = (Impressora) this.getObjectSelectOnGrid();
        
        List<Fornecedor> eqFornecedores= impressoraTab.getFornecedor();
        
        DefaultListModel delistFornecedor = new DefaultListModel();
        
        for (Fornecedor eqFornecedor : eqFornecedores) {
            delistFornecedor.addElement("Id: " + eqFornecedor.getId()
                    + " | Nome: " + eqFornecedor.getNome());
        }
        
        lstFornecedor.setModel(delistFornecedor);
    }
    
    private void preencherListaServicosAdicionais(){
        Impressora equinoTab = (Impressora) this.getObjectSelectOnGrid();
        
        List<ImpressoraServico> impServicos = equinoTab.getImpressoraServico();
        
        DefaultListModel delistServicos = new DefaultListModel();
        
        for (ImpressoraServico impServico : impServicos) {
            delistServicos.addElement("Id: " + impServico.getServicoAdicional().getId()
                    + " | Nome: " + impServico.getServicoAdicional().getServico()
                    + " | Quantidade: " + impServico.getQtd());
        }
        
        lstServicosAdicional.setModel(delistServicos);
    }

    
    
    private Object getObjectSelectOnGrid() {
        int rowCliked = grdImpressora.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdImpressora.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdImpressora = new javax.swing.JTable();
        lblSubtitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstServicosAdicional = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFornecedor = new javax.swing.JList<>();
        lblAlimentos = new javax.swing.JLabel();
        lblServicosAdicionais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Tecnicos");

        grdImpressora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdImpressora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdImpressoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdImpressora);

        lblSubtitulo.setText("Selecione uma impressora:");

        lstServicosAdicional.setEnabled(false);
        jScrollPane2.setViewportView(lstServicosAdicional);

        lstFornecedor.setEnabled(false);
        jScrollPane3.setViewportView(lstFornecedor);

        lblAlimentos.setText("Fornecedor:");

        lblServicosAdicionais.setText("Serviços adicionais:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubtitulo)
                            .addComponent(lblAlimentos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServicosAdicionais)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlimentos)
                    .addComponent(lblServicosAdicionais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grdImpressoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdImpressoraMouseClicked
        if (evt.getClickCount() == 2) {
            preencherListaFornecedor();
            preencherListaServicosAdicionais();
        }
    }//GEN-LAST:event_grdImpressoraMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grdImpressora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlimentos;
    private javax.swing.JLabel lblServicosAdicionais;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstFornecedor;
    private javax.swing.JList<String> lstServicosAdicional;
    // End of variables declaration//GEN-END:variables
}
