/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.view;

/**
 *
 * @author JonathasOliveira
 */
public class FrAtendente extends javax.swing.JFrame {

    /**
     * Creates new form FrAtendente
     */
    public FrAtendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFormularioAtendente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCadastros = new javax.swing.JLabel();
        btnClienteAtendente = new javax.swing.JButton();
        btnFuncionarioAtendente = new javax.swing.JButton();
        btnImpressoraAtendente = new javax.swing.JButton();
        lblRelatorios = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Locação de Impressora");

        lblCadastros.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblCadastros.setText("Cadastros:");

        btnClienteAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClienteAtendente.setText("Cliente");
        btnClienteAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteAtendenteActionPerformed(evt);
            }
        });

        btnFuncionarioAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFuncionarioAtendente.setText("Funcionario");
        btnFuncionarioAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionarioAtendenteActionPerformed(evt);
            }
        });

        btnImpressoraAtendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnImpressoraAtendente.setText("Impressora");
        btnImpressoraAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpressoraAtendenteActionPerformed(evt);
            }
        });

        lblRelatorios.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        lblRelatorios.setText("Relatorios:");

        javax.swing.GroupLayout panFormularioAtendenteLayout = new javax.swing.GroupLayout(panFormularioAtendente);
        panFormularioAtendente.setLayout(panFormularioAtendenteLayout);
        panFormularioAtendenteLayout.setHorizontalGroup(
            panFormularioAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioAtendenteLayout.createSequentialGroup()
                .addGroup(panFormularioAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFormularioAtendenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panFormularioAtendenteLayout.createSequentialGroup()
                        .addGroup(panFormularioAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFormularioAtendenteLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClienteAtendente)
                                .addGap(49, 49, 49)
                                .addComponent(btnFuncionarioAtendente)
                                .addGap(55, 55, 55)
                                .addComponent(btnImpressoraAtendente))
                            .addGroup(panFormularioAtendenteLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblRelatorios)))
                        .addGap(0, 175, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panFormularioAtendenteLayout.setVerticalGroup(
            panFormularioAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioAtendenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panFormularioAtendenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteAtendente)
                    .addComponent(btnFuncionarioAtendente)
                    .addComponent(btnImpressoraAtendente))
                .addGap(67, 67, 67)
                .addComponent(lblRelatorios)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFormularioAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFormularioAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteAtendenteActionPerformed

    private void btnFuncionarioAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionarioAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFuncionarioAtendenteActionPerformed

    private void btnImpressoraAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpressoraAtendenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImpressoraAtendenteActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteAtendente;
    private javax.swing.JButton btnFuncionarioAtendente;
    private javax.swing.JButton btnImpressoraAtendente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCadastros;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JPanel panFormularioAtendente;
    // End of variables declaration//GEN-END:variables
}
