/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.model.view;


//bibiliotecas para gerar o contrato em pdf (se necessário)
/*import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;*/ 

/**
 *
 * @author JonathasOliveira
 */
public class FrCadastroContrato extends javax.swing.JFrame {

    /**
     * Creates new form FrCadastroContrato
     */
    public FrCadastroContrato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panFormularioContrato = new javax.swing.JPanel();
        lblCadastroContratos = new javax.swing.JLabel();
        lblNumContrato = new javax.swing.JTextField();
        edtNumeroContrato = new javax.swing.JTextField();
        lblNomeContrato = new javax.swing.JLabel();
        edtClienteContrato = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        lblValorContrato = new javax.swing.JLabel();
        edtValorContrato = new javax.swing.JTextField();
        lblEnderecoContrato = new javax.swing.JLabel();
        edtEnderecoContrato = new javax.swing.JTextField();
        btnGerarContrato = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastroContratos.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblCadastroContratos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastroContratos.setText("Cadastro de Contratos");

        lblNumContrato.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblNumContrato.setText("Número do Contrato: ");

        lblNomeContrato.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblNomeContrato.setText("Nome do Cliente: ");

        lblCpf.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblCpf.setText("CPF/CNPJ: ");

        lblValorContrato.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblValorContrato.setText("Valor do Contrato:");

        lblEnderecoContrato.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblEnderecoContrato.setText("Endereço do Cliente: ");

        btnGerarContrato.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnGerarContrato.setText("Gerar Contrato");
        btnGerarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFormularioContratoLayout = new javax.swing.GroupLayout(panFormularioContrato);
        panFormularioContrato.setLayout(panFormularioContratoLayout);
        panFormularioContratoLayout.setHorizontalGroup(
            panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFormularioContratoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCadastroContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFormularioContratoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                                .addComponent(lblNumContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                                .addComponent(lblNomeContrato)
                                .addGap(18, 18, 18)
                                .addComponent(edtClienteContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                                .addComponent(lblCpf)
                                .addGap(26, 26, 26)
                                .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                                .addComponent(lblEnderecoContrato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtEnderecoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                                .addComponent(lblValorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtValorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFormularioContratoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGerarContrato)
                .addGap(50, 50, 50))
        );
        panFormularioContratoLayout.setVerticalGroup(
            panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioContratoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCadastroContratos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtClienteContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtEnderecoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panFormularioContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorContrato)
                    .addComponent(edtValorContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnGerarContrato)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFormularioContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFormularioContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadastroContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadastroContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadastroContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadastroContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadastroContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarContrato;
    private javax.swing.JTextField edtClienteContrato;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtEnderecoContrato;
    private javax.swing.JTextField edtNumeroContrato;
    private javax.swing.JTextField edtValorContrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCadastroContratos;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEnderecoContrato;
    private javax.swing.JLabel lblNomeContrato;
    private javax.swing.JTextField lblNumContrato;
    private javax.swing.JLabel lblValorContrato;
    private javax.swing.JPanel panFormularioContrato;
    // End of variables declaration//GEN-END:variables
}
